parameters:
    ger.cmbb.tables.cms_article: '%core.table_prefix%cms_article'
    ger.cmbb.tables.cms_category: '%core.table_prefix%cms_category'
    ger.cmbb.tables.cms_config: '%core.table_prefix%cms_config'
    ger.cmbb.tables.cms_template: '%core.table_prefix%cms_template'
